version: '3'
services:
  spark-master:
    image: atahualpa/spark-master:gatk4.1.1
    networks:
      - workbench
    deploy:
      replicas: 1
      mode: replicated
      restart_policy:
        condition: on-failure
      labels:
       traefik.docker.network: workbench
       traefik.port: 8080
    env_file:
      - ./hadoop.env
    ports:
      - 8333:8080
      - 4040:4040
      - 6066:6066
      - 7077:7077
    volumes:
      - /data0/reference/hg19-ucsc/:/reference/hg19-ucsc/
      - /data0/fastq/:/fastq/
      - /data0/NGS-SparkGATK/NGS-SparkGATK/:/NGS-SparkGATK/
      - /data/ngs/:/ngs/
  spark-worker:
    image: bde2020/spark-worker:2.2.0-hadoop2.8-hive-java8
    networks:
      - workbench
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
      labels:
        traefik.docker.network: workbench
        traefik.port: 8081

    env_file:
      - ./hadoop.env
    volumes:
      - reference-image:/reference_image

  reference:
    image: vzzarr/reference:hg19_img
    networks:
      - workbench
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    tty: true    #keeps the container alive
    volumes:
      - reference-image:/reference_image

volumes:
  reference-image:

networks:
  workbench:
    external: true