version: '3.2' 
services:
  spark-master:
    image: vzzarr/spark-master:gatk4_0_2
    networks:
      - core
    deploy:
      replicas: 1
      mode: replicated
      restart_policy:
        condition: on-failure
    ports:
      - 4040:4040
      - 6066:6066
      - 8080:8080
      - 7077:7077
    env_file:
      - ./hadoop-swarm.env
    volumes:
      - /data0/reference/hg19-ucsc/:/reference/hg19-ucsc/
      - /data0/fastq/:/fastq/
      - ../../:/NGS-SparkGATK/
      - /data/ngs/:/ngs/
  spark-worker:
    image: bde2020/spark-worker:2.2.0-hadoop2.8-hive-java8
    networks:
      - core
    environment:
      - SPARK_MASTER=spark://spark-master:7077
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    ports:
      - 8081:8081
    env_file:
      - ./hadoop-swarm.env
    volumes:
      - reference-image:/reference_image

  reference:
    image: vzzarr/reference:hg19_img
    networks:
      - core
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    tty: true    #keeps the container alive
    volumes:
      - reference-image:/reference_image

volumes:
  reference-image:

networks:
  core:
    external: true
